/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /* tutorialSidebar: [{type: 'autogenerated', dirName: '.'}], */

  // But you can create a sidebar manually

  // English sidebar nav
  docsEnglish: [
    {
      type: 'doc',
      label: 'ScalarDL Docs Home',
      id: 'index',
    },
    {
      type: 'category',
      label: 'About ScalarDL',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'design',
          label: 'Design',
        },
        {
          type: 'doc',
          id: 'implementation',
          label: 'Implementation',
        },
        {
          type: 'doc',
          id: 'glossary',
          label: 'Glossary',
        },
        {
          type: 'doc',
          id: 'requirements',
          label: 'Requirements',
        },
        {
          type: 'doc',
          id: 'releases/release-notes',
          label: 'Release Notes',
        },
        {
          type: 'doc',
          id: 'releases/release-support-policy',
          label: 'Release Support Policy',
        },
        {
          type: 'doc',
          id: 'roadmap',
          label: 'Roadmap',
        },
      ]
    },
    {
      type: 'category',
      label: 'Quickstart',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'quickstart-overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'getting-started',
          label: 'Run a Contract Through ScalarDL Ledger',
        },
      ],
    },
    {
      type: 'category',
      label: 'Develop',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'data-modeling',
          label: 'Model Your Data',
        },
        {
          type: 'doc',
          id: 'how-to-write-contract',
          label: 'Write a Contract',
        },
        {
          type: 'doc',
          id: 'how-to-write-function',
          label: 'Write a Function',
        },
        {
          type: 'doc',
          id: 'use-generic-contracts',
          label: 'Use Generic Contracts',
        },
        {
          type: 'category',
          label: 'Write an Application',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'how-to-write-applications',
              label: 'Write an Application in Java',
            },
            {
              type: 'doc',
              id: 'how-to-write-applications-with-generic-contracts',
              label: 'Write an Application with Generic Contracts',
            },
          ]
        },
        {
          type: 'category',
          label: 'Run an Application',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'getting-started-auditor',
              label: 'Run a Contract Through ScalarDL Ledger and Auditor',
            },
          ]
        },
        {
          type: 'category',
          label: 'Run Sample Applications',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'applications/simple-bank-account/README',
              label: 'Bank Account Application',
            },
          ],
        },
        {
          type: 'category',
          label: 'Advanced Configurations and Operations',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'authentication',
              label: 'Authentication',
            },
            {
              type: 'doc',
              id: 'scalardl-benchmarks/README',
              label: 'Run Benchmarks',
            },
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'compatibility',
              label: 'Compatibility Matrix',
            },
            {
              type: 'doc',
              id: 'configurations',
              label: 'Configurations',
            },
            {
              type: 'doc',
              id: 'scalardl-command-reference',
              label: 'Client Commands',
            },
            {
              type: 'doc',
              id: 'schema-loader',
              label: 'ScalarDL Schema Loader',
            },
            {
              type: 'doc',
              id: 'generic-contracts-reference',
              label: 'Generic Contracts',
            },
            {
              type: 'doc',
              id: 'ca/caclient-getting-started',
              label: 'Get a Certificate',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Deploy',
      collapsible: true,
      items: [
        {
          type: 'category',
          label: 'Scalar Kubernetes',
          collapsible: true,
          items: [
            {
              type: 'category',
              label: 'Database Setup Guides',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/SetupDatabaseForAWS',
                  label: 'Databases on AWS',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/SetupDatabaseForAzure',
                  label: 'Databases on Azure',
                },
              ],
            },
            {
              type: 'category',
              label: 'Installation Guides',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/ProductionChecklistForScalarDLLedger',
                  label: 'Production checklist for ScalarDL Ledger',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/ProductionChecklistForScalarDLAuditor',
                  label: 'Production checklist for ScalarDL Auditor',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/AwsMarketplaceGuide',
                  label: 'Install from AWS Marketplace',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/AzureMarketplaceGuide',
                  label: 'Install from Azure Marketplace',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/CreateBastionServer',
                  label: 'Create a Bastion Server',
                },
              ],
            },
            {
              type: 'category',
              label: 'Cluster Guides',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/CreateEKSClusterForScalarDL',
                  label: 'Create an EKS Cluster for ScalarDL Ledger',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/CreateEKSClusterForScalarDLAuditor',
                  label: 'Create an EKS Cluster for ScalarDL Ledger and Auditor',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/CreateAKSClusterForScalarDL',
                  label: 'Create an AKS cluster for ScalarDL Ledger',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/CreateAKSClusterForScalarDLAuditor',
                  label: 'Create an AKS cluster for ScalarDL Ledger and Auditor',
                },
              ],
            },
            {
              type: 'category',
              label: 'Container Image Guides',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/HowToGetContainerImages',
                  label: 'Get Container Images',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/HowToUseContainerImages',
                  label: 'Use Container Images',
                },
              ],
            },
            {
              type: 'category',
              label: 'Deployment Guides',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/ManualDeploymentGuideScalarDLOnEKS',
                  label: 'Deploy ScalarDL Ledger on Amazon EKS',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/ManualDeploymentGuideScalarDLAuditorOnEKS',
                  label: 'Deploy ScalarDL Ledger and Auditor on Amazon EKS',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/ManualDeploymentGuideScalarDLOnAKS',
                  label: 'Deploy ScalarDL Ledger on AKS',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/ManualDeploymentGuideScalarDLAuditorOnAKS',
                  label: 'Deploy ScalarDL Ledger and Auditor on AKS',
                },
              ],
            },
            {
              type: 'category',
              label: 'Configuration Guides',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/AccessScalarProducts',
                  label: 'Access Kubernetes Environment from Applications',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/HowToCreateKeyAndCertificateFiles',
                  label: 'Create Private Key and Certificate Files',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/NetworkPeeringForScalarDLAuditor',
                  label: 'Configure Network Peering for ScalarDL Auditor',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Scalar Helm Charts',
          collapsible: true,
          items: [
            {
              type: 'category',
              label: 'Getting Started',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalar-helm-charts',
                  label: 'Use Scalar Helm Charts',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalardl-ledger',
                  label: 'ScalarDL Ledger by Using a Helm Chart',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalardl-auditor',
                  label: 'ScalarDL Ledger and Auditor by Using a Helm Chart',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalardl-auditor-tls',
                  label: 'ScalarDL Ledger and Auditor with TLS by Using a Helm Chart',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalardl-auditor-tls-cert-manager',
                  label: 'ScalarDL Ledger and Auditor with TLS by Using cert-manager and a Helm Chart',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-monitoring',
                  label: 'Prometheus Operator for Monitoring by Using a Helm Chart',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-logging',
                  label: 'Loki Stack for Logging by Using a Helm Chart by Using a Helm Chart',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalar-manager',
                  label: 'Scalar Manager by Using a Helm Chart',
                },
              ]
            },
            {
              type: 'category',
              label: 'Configure Custom Values',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalardl-ledger',
                  label: 'Configure a Custom Values File for ScalarDL Ledger',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalardl-auditor',
                  label: 'Configure a Custom Values File for ScalarDL Auditor',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalardl-schema-loader',
                  label: 'Configure a Custom Values File for ScalarDL Schema Loader',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalar-admin-for-kubernetes',
                  label: 'Configure a Custom Values File for Scalar Admin for Kubernetes',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalar-manager',
                  label: 'Configure a Custom Values File for Scalar Manager',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-envoy',
                  label: 'Configure a Custom Values File for Scalar Envoy',
                },
              ],
            },
            {
              type: 'doc',
              id: 'helm-charts/how-to-deploy-scalar-products',
              label: 'Deploy Scalar Products Using Scalar Helm Charts',
            },
            {
              type: 'doc',
              id: 'helm-charts/how-to-deploy-scalardl-ledger',
              label: 'Deploy ScalarDL Ledger',
            },
            {
              type: 'doc',
              id: 'helm-charts/how-to-deploy-scalardl-auditor',
              label: 'Deploy ScalarDL Auditor',
            },
            {
              type: 'doc',
              id: 'helm-charts/how-to-deploy-scalar-admin-for-kubernetes',
              label: 'Deploy Scalar Admin for Kubernetes',
            },
            {
              type: 'doc',
              id: 'helm-charts/mount-files-or-volumes-on-scalar-pods',
              label: 'Mount Files or Volumes on ScalarDL Pods',
            },
            {
              type: 'doc',
              id: 'helm-charts/use-secret-for-credentials',
              label: 'Use Secret Resources',
            },
          ],
        },
        {
          type: 'doc',
          id: 'scalar-licensing/README',
          label: 'Configure a Product License Key',
        },
        {
          type: 'doc',
          id: 'installation-with-docker',
          label: 'Install ScalarDL in Your Local Environment with Docker',
        },
        {
          type: 'doc',
          id: 'ca/caserver-getting-started',
          label: 'Start CA Server with CFSSL',
        },
      ],
    },
    {
      type: 'category',
      label: 'Manage',
      collapsible: true,
      items: [
        {
          type: 'category',
          label: 'Scalar Kubernetes',
          collapsible: true,
          items: [
            {
              type: 'category',
              label: 'Monitoring Guides',
              collapsible: true,
              items: [
                {
                  type: 'category',
                  label: 'Alerts',
                  collapsible: true,
                  items: [
                    {
                      type: 'doc',
                      id: 'scalar-kubernetes/alerts/Envoy',
                      label: 'Envoy Alerts',
                    },
                    {
                      type: 'doc',
                      id: 'scalar-kubernetes/alerts/Ledger',
                      label: 'Ledger Alerts',
                    },
                  ],
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/K8sMonitorGuide',
                  label: 'Kubernetes Monitoring Guide',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/K8sLogCollectionGuide',
                  label: 'Collect Logs from ScalarDL on a Kubernetes Cluster',
                },
              ],
            },
            {
              type: 'category',
              label: 'Backup and Restore Guides',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/BackupRestoreGuide',
                  label: 'Back Up and Restore ScalarDL Data in Kubernetes',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/BackupRDB',
                  label: 'Back Up an RDB in Kubernetes',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/BackupNoSQL',
                  label: 'Back Up a NoSQL Database in Kubernetes',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/RestoreDatabase',
                  label: 'Restore Databases in Kubernetes',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/RegularCheck',
                  label: 'Components to Regularly Check When Running on Kubernetes',
                },
              ],
            },
          ],
        },
        {
          type: 'doc',
          id: 'backup-restore',
          label: 'Backup and Restore Data',
        },
        {
          type: 'doc',
          id: 'scalar-kubernetes/HowToScaleScalarDL',
          label: 'Scale',
        },
        {
          type: 'doc',
          id: 'scalar-kubernetes/HowToUpgradeScalarDL',
          label: 'Upgrade',
        },
        {
          type: 'doc',
          id: 'scalar-manager/overview',
          label: 'Scalar Manager Overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: true,
      items: [
        
        
        {
          type: 'category',
          label: 'Error codes',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardl-common-status-codes',
              label: 'ScalarDL Common Error Codes',
            },
            {
              type: 'doc',
              id: 'scalardl-ledger-status-codes',
              label: 'ScalarDL Ledger Error Codes',
            },
            {
              type: 'doc',
              id: 'scalardl-auditor-status-codes',
              label: 'ScalarDL Auditor Error Codes',
            },
            {
              type: 'doc',
              id: 'scalardl-client-status-codes',
              label: 'ScalarDL Client Error Codes',
            },
          ],
        },
      ],
    },
  ],

  // Japanese sidebar nav
  docsJapanese: [
    {
      type: 'doc',
      label: 'ScalarDL ドキュメンテーションホーム',
      id: 'index',
    },
    {
      type: 'category',
      label: 'ScalarDL について',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'overview',
          label: '概要',
        },
        {
          type: 'doc',
          id: 'design',
          label: 'デザイン',
        },
        {
          type: 'doc',
          id: 'implementation',
          label: '実装',
        },
        {
          "type": "doc",
          "id": "glossary",
          "label": "用語集",
        },
        {
          type: 'doc',
          id: 'requirements',
          label: '要件',
        },
        {
          type: 'doc',
          id: 'releases/release-notes',
          label: 'リリースノート',
        },
        {
          type: 'doc',
          id: 'releases/release-support-policy',
          label: 'リリースサポートポリシー',
        },
        {
          type: 'doc',
          id: 'roadmap',
          label: 'ロードマップ',
        },
      ]
    },
    {
      type: 'category',
      label: 'クイックスタート',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'quickstart-overview',
          label: '概要',
        },
        {
          type: 'doc',
          id: 'getting-started',
          label: 'ScalarDL Ledger を通じてコントラクトを実行',
        },
      ],
    },
    {
      type: 'category',
      label: '開発',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'data-modeling',
          label: 'データモデリング',
        },
        {
          type: 'doc',
          id: 'how-to-write-contract',
          label: 'コントラクトを作成',
        },
        {
          type: 'doc',
          id: 'how-to-write-function',
          label: 'ファンクションを作成',
        },
        {
          type: 'doc',
          id: 'use-generic-contracts',
          label: '汎用コントラクトを使用',
        },
        {
          type: 'category',
          label: 'アプリケーションを書く',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'how-to-write-applications',
              label: 'Java でアプリケーションを書く',
            },
            {
              type: 'doc',
              id: 'how-to-write-applications-with-generic-contracts',
              label: '汎用コントラクトを用いたアプリケーションを作成',
            },
          ]
        },
        {
          type: 'category',
          label: 'アプリケーションを実行',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'getting-started-auditor',
              label: 'ScalarDL Ledger と Auditor を通じてコントラクトを実行',
            },
          ]
        },
        {
          type: 'category',
          label: 'サンプルアプリケーションを実行',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'applications/simple-bank-account/README',
              label: '銀行口座アプリケーション',
            },
          ],
        },
        {
          type: 'category',
          label: '高度な設定と操作',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'authentication',
              label: '認証',
            },
            {
              type: 'doc',
              id: 'scalardl-benchmarks/README',
              label: 'ベンチマークを実行',
            },
          ],
        },
        {
          type: 'category',
          label: '詳細',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'compatibility',
              label: '互換性マトリックス',
            },
            {
              type: 'doc',
              id: 'configurations',
              label: '設定',
            },
            {
              type: 'doc',
              id: 'scalardl-command-reference',
              label: 'クライアントコマンドリファレンス',
            },
            {
              type: 'doc',
              id: 'schema-loader',
              label: 'ScalarDL Schema Loader',
            },
            {
              type: 'doc',
              id: 'generic-contracts-reference',
              label: '汎用コントラクト',
            },
            {
              type: 'doc',
              id: 'ca/caclient-getting-started',
              label: '証明書を取得',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'デプロイ',
      collapsible: true,
      items: [
        {
          type: 'category',
          label: 'Scalar Kubernetes',
          collapsible: true,
          items: [
            {
              type: 'category',
              label: 'データベースセットアップガイド',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/SetupDatabaseForAWS',
                  label: 'AWS が提供するデータベース',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/SetupDatabaseForAzure',
                  label: 'Azure が提供するデータベース',
                },
              ],
            },
            {
              type: 'category',
              label: 'インストールガイド',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/ProductionChecklistForScalarDLLedger',
                  label: 'ScalarDL Ledger の本番環境チェックリスト',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/ProductionChecklistForScalarDLAuditor',
                  label: 'ScalarDL Auditor の本番環境チェックリスト',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/AwsMarketplaceGuide',
                  label: 'AWS Marketplace からインストール',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/AzureMarketplaceGuide',
                  label: 'Azure Marketplace からインストール',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/CreateBastionServer',
                  label: '踏み台サーバーを作成',
                },
              ],
            },
            {
              type: 'category',
              label: 'クラスターガイド',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/CreateEKSClusterForScalarDL',
                  label: 'ScalarDL Ledger 用の EKS クラスターを作成',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/CreateEKSClusterForScalarDLAuditor',
                  label: 'ScalarDL Ledger と Auditor 用の EKS クラスターを作成',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/CreateAKSClusterForScalarDL',
                  label: 'ScalarDL Ledger 用の AKS クラスターを作成',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/CreateAKSClusterForScalarDLAuditor',
                  label: 'ScalarDL Ledger と Auditor 用の AKS クラスターを作成',
                },
              ],
            },
            {
              type: 'category',
              label: 'コンテナイメージガイド',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/HowToGetContainerImages',
                  label: 'コンテナイメージを取得',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/HowToUseContainerImages',
                  label: 'コンテナイメージを使用',
                },
              ],
            },
            {
              type: 'category',
              label: 'デプロイメントガイド',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/ManualDeploymentGuideScalarDLOnEKS',
                  label: 'Amazon EKS に ScalarDL Ledger をデプロイ',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/ManualDeploymentGuideScalarDLAuditorOnEKS',
                  label: 'Amazon EKS に ScalarDL Ledger と Auditorをデプロイ',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/ManualDeploymentGuideScalarDLOnAKS',
                  label: 'AKS に ScalarDL Ledger をデプロイ',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/ManualDeploymentGuideScalarDLAuditorOnAKS',
                  label: 'AKS に ScalarDL Ledger と Auditor をデプロイ',
                },
              ],
            },
            {
              type: 'category',
              label: '設定のガイド',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/AccessScalarProducts',
                  label: 'アプリケーションから Kubernetes 環境にアクセス',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/HowToCreateKeyAndCertificateFiles',
                  label: '秘密鍵と証明書ファイルを作成',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/NetworkPeeringForScalarDLAuditor',
                  label: 'ネットワークピアリングを構成',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Scalar Helm Charts',
          collapsible: true,
          items: [
            {
              type: 'category',
              label: 'はじめよう',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalar-helm-charts',
                  label: 'Scalar Helm Charts をはじめよう',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalardl-ledger',
                  label: 'Helm Chart を使用した ScalarDL Ledger',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalardl-auditor',
                  label: 'Helm Chart を使用した ScalarDL Ledger と Auditor',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalardl-auditor-tls',
                  label: 'Helm Chart を使用した TLS 対応 ScalarDL Ledger と Auditor',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalardl-auditor-tls-cert-manager',
                  label: 'cert-manager と Helm Chart を使用した TLS 対応 ScalarDL Ledger と Auditor',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-monitoring',
                  label: 'Helm Chart を使用した監視用 Prometheus Operator',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-logging',
                  label: 'Helm Chart を使用したログ記録用 Loki スタック',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalar-manager',
                  label: 'Helm Chart を使用した Scalar Manager',
                },
              ]
            },
            {
              type: 'category',
              label: 'カスタム値を設定',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalardl-ledger',
                  label: 'ScalarDL Ledger のカスタム値ファイルを構成',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalardl-auditor',
                  label: 'ScalarDL Auditor のカスタム値ファイルを構成',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalardl-schema-loader',
                  label: 'ScalarDL Schema Loader のカスタム値ファイルを構成',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalar-admin-for-kubernetes',
                  label: 'Scalar Admin for Kubernetes のカスタム値ファイルを構成',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalar-manager',
                  label: 'Scalar Manager のカスタム値ファイルを構成',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-envoy',
                  label: 'Scalar Envoy のカスタム値ファイルを構成',
                },
              ],
            },
            {
              type: 'doc',
              id: 'helm-charts/how-to-deploy-scalar-products',
              label: 'Helm Chart を使用して Scalar 製品をデプロイ',
            },
            {
              type: 'doc',
              id: 'helm-charts/how-to-deploy-scalardl-ledger',
              label: 'Helm Chart を使用して ScalarDL Ledger をデプロイ',
            },
            {
              type: 'doc',
              id: 'helm-charts/how-to-deploy-scalardl-auditor',
              label: 'Helm Chart を使用して ScalarDL Auditor をデプロイ',
            },
            {
              type: 'doc',
              id: 'helm-charts/how-to-deploy-scalar-admin-for-kubernetes',
              label: 'Helm Chart を使用して Scalar Admin for Kubernetes をデプロイ',
            },
            {
              type: 'doc',
              id: 'helm-charts/mount-files-or-volumes-on-scalar-pods',
              label: 'ScalarDL ポッドにファイルまたはボリュームをマウント',
            },
            {
              type: 'doc',
              id: 'helm-charts/use-secret-for-credentials',
              label: 'シークレットリソースを使用',
            },
          ],
        },
        {
          type: 'doc',
          id: 'scalar-licensing/README',
          label: '製品ライセンスキーの設定',
        },
        {
          type: 'doc',
          id: 'installation-with-docker',
          label: 'Docker を使ってローカル環境に ScalarDL をインストール',
        },
        {
          type: 'doc',
          id: 'ca/caserver-getting-started',
          label: 'CFSSL で CA サーバーを起動',
        },
      ],
    },
    {
      type: 'category',
      label: '運用',
      collapsible: true,
      items: [
        {
          type: 'category',
          label: 'Scalar Kubernetes',
          collapsible: true,
          items: [
            {
              type: 'category',
              label: 'モニタリングガイド',
              collapsible: true,
              items: [
                {
                  type: 'category',
                  label: 'アラート',
                  collapsible: true,
                  items: [
                    {
                      type: 'doc',
                      id: 'scalar-kubernetes/alerts/Envoy',
                      label: 'Envoy アラート',
                    },
                    {
                      type: 'doc',
                      id: 'scalar-kubernetes/alerts/Ledger',
                      label: 'Ledger アラート',
                    },
                  ],
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/K8sMonitorGuide',
                  label: 'Kubernetes モニタリングガイド',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/K8sLogCollectionGuide',
                  label: 'Kubernetes ログ収集ガイド',
                },
              ],
            },
            {
              type: 'category',
              label: 'バックアップと復元のガイド',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/BackupRestoreGuide',
                  label: 'Kubernetes 環境で ScalarDL データをバックアップおよび復元',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/BackupRDB',
                  label: 'Kubernetes 環境で RDB をバックアップ',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/BackupNoSQL',
                  label: 'Kubernetes 環境で NoSQL データベースをバックアップ',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/RestoreDatabase',
                  label: 'Kubernetes 環境でデータベースを復元',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/RegularCheck',
                  label: 'Kubernetes 環境で実行するときに定期的にチェックするコンポーネント',
                },
              ],
            },
          ],
        },
        {
          type: 'doc',
          id: 'backup-restore',
          label: 'データのバックアップと復元',
        },
        {
          type: 'doc',
          id: 'scalar-kubernetes/HowToScaleScalarDL',
          label: 'スケーリング',
        },
        {
          type: 'doc',
          id: 'scalar-kubernetes/HowToUpgradeScalarDL',
          label: 'アップグレード',
        },
        {
          type: 'doc',
          id: 'scalar-manager/overview',
          label: 'Scalar Manager の概要',
        },
      ],
    },
    {
      type: 'category',
      label: '詳細',
      collapsible: true,
      items: [
        {
          type: 'category',
          label: 'Error codes',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardl-common-status-codes',
              label: 'ScalarDL 共通エラーコード',
            },
            {
              type: 'doc',
              id: 'scalardl-ledger-status-codes',
              label: 'ScalarDL Ledger エラーコード',
            },
            {
              type: 'doc',
              id: 'scalardl-auditor-status-codes',
              label: 'ScalarDL Auditor エラーコード',
            },
            {
              type: 'doc',
              id: 'scalardl-client-status-codes',
              label: 'ScalarDL クライアントエラーコード',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
